#!/usr/bin/env python3
"""
Action Potential Curve Fitter
══════════════════════════════════════════════════════════════════════════════
Fits the six parameters of the piecewise ODE action-potential model
(potential(t), solved via Laplace transform from  jv'' + kv' + lv = 0)
to an observed set of (time, voltage) data points.

Objective minimised:
    E(params) = Σ_i [ potential(t_i ; params) − y_i ]²

Optimiser: scipy.optimize.minimize, method='Nelder-Mead'
    · Derivative-free simplex method; safe at the piecewise boundaries.
    · The discriminant constraint  k² < 4jl  is enforced via a 1e12
      penalty — no gradient or explicit constraint objects needed.
    · The quality of convergence depends on the quality of the initial
      guess.  The defaults here are taken directly from the hardcoded
      values in potential(t), so they are ideal when fitting data that
      was generated by (or is similar to) that function.
    
    

NOTE ON IDENTIFIABILITY
    The ODE solution shape is determined by the ratio k/(2j) (decay rate)
    and Q = sqrt((4jl−k²)/4j²) (oscillation frequency), not by j, k, l
    individually.  Different (j,k,l) triples can produce very similar
    waveforms, so parameter recovery from noisy data is not unique.
    What IS reliable is the model fit itself: the fitted curve will closely
    match the observed data regardless of which valid (j,k,l) the optimiser
    settles on.  If you need unique ODE coefficients, supplement the data
    with independent measurements (e.g. impedance spectroscopy).

Dependencies: numpy, scipy   (pip install numpy scipy)

HOW TO USE
----------
    from ap_curve_fitter import fit_potential, evaluate

    # x: time array (ms), y: voltage array (mV) — same length
    params = fit_potential(x, y)
    # Returns np.ndarray([mg, b, j, k, l, base])

    # Optional: evaluate the fitted model on a dense grid
    y_hat = evaluate(t_grid, params)
"""

import math as m
import numpy as np
from typing import Optional
from scipy.optimize import minimize, OptimizeResult


# ══════════════════════════════════════════════════════════════════════════════
# ORIGINAL POTENTIAL FUNCTION  (reproduced verbatim from user specification)
# ══════════════════════════════════════════════════════════════════════════════

# Solved for ODE jv''+kv'+lv=0 using laplace transform
def potential(t):
    # --- Parameters ---
    mg = 402.2442 # Gradient of line
    b = 0.1662 # v(0) for DHM initial condition
    j = 0.0261 # Strength of restorative force (equivalent to spring constant in DHM system)
    k = 0.0771 # 0 < k < sqrt(4jl), or else you'll get complex solutions or cause the resistive term to add to jv''
    l = 0.0570 # Constant of proportionality
    base = -67.85 # Baseline potential
    shift = b/mg + 5 # Ability to shift along time axis (controls point of start for linear section)
    # ------------------

    Q = m.sqrt((4*j*l-k**2)/(4*j**2)) # Equivalent to big K from book
    C = mg + b*k/(2*j)
    t -= shift # Shifts graph to right by shift value

    # --- Piecewise Function ---
    if t<-b/mg: # Baseline
        y = base
    elif -b/mg <= t < 0: # Depolarisation
        y = mg*t+b+base
    elif t>=0: # Repolarisation, Hyperpolarisation and return to baseline value
        y = m.exp(-k*t/(2*j))* (b*m.cos(Q*t) + C/Q*m.sin(Q*t))+base
    #---------------------------
    return y


# ══════════════════════════════════════════════════════════════════════════════
# PARAMETRIC VERSION  (identical maths; all six params taken as arguments)
# ══════════════════════════════════════════════════════════════════════════════

def _potential_parametric(t: float,
                            mg: float, b: float, j: float,
                            k: float, l: float, base: float) -> float:
    """
    Identical to potential(t) but receives all six parameters as arguments
    rather than reading hardcoded values. Used internally by the fitter so
    the optimiser can evaluate the model at arbitrary parameter values.

    The caller must ensure k² < 4jl holds before calling — otherwise
    m.sqrt raises ValueError.
    """
    shift = b / mg + 5
    Q     = m.sqrt((4 * j * l - k ** 2) / (4 * j ** 2))
    C     = mg + b * k / (2 * j)
    t    -= shift

    if t < -b / mg:                   # Baseline
        return base
    elif -b / mg <= t < 0:            # Depolarisation (linear)
        return mg * t + b + base
    else:                              # Repolarisation / AHP / recovery
        return m.exp(-k * t / (2 * j)) * (b * m.cos(Q * t) + C / Q * m.sin(Q * t)) + base


# ══════════════════════════════════════════════════════════════════════════════
# PARAMETER METADATA
# ══════════════════════════════════════════════════════════════════════════════

# Six parameter names in the order they appear in potential(t) and in the
# array returned by fit_potential().
PARAM_NAMES: list[str] = ["mg", "b", "j", "k", "l", "base"]

# Initial guesses taken directly from the hardcoded values in potential(t).
# These are passed to the optimiser as x0 when the caller does not supply
# their own initial_params.
INITIAL_PARAMS: np.ndarray = np.array(
    [402.2442, 0.1662, 0.0261, 0.0771, 0.0570, -67.85],
    dtype=float,
)


# ══════════════════════════════════════════════════════════════════════════════
# OBJECTIVE FUNCTION
# ══════════════════════════════════════════════════════════════════════════════

def _make_objective(x: np.ndarray, y: np.ndarray):
    """
    Build and return a closure over (x, y) that computes:

        E(params) = Σ_i [ _potential_parametric(x_i ; params) − y_i ]²

    Invalid parameters are handled by a large penalty (1e12):
        · j, k, l must be strictly positive  (required for real Q)
        · mg must be non-zero                (appears as denominator in shift)
        · k² < 4jl must hold strictly        (discriminant condition — ensures
                                              the solution is oscillatory, not
                                              overdamped or critically damped)
    """
    def objective(params: np.ndarray) -> float:
        mg, b, j, k, l, base = params

        # --- Validity guards ---
        if j <= 0.0 or k <= 0.0 or l <= 0.0:
            return 1e12
        if abs(mg) < 1e-10:           # mg appears as denominator in shift = b/mg + 5
            return 1e12
        if k ** 2 >= 4.0 * j * l:    # Discriminant must be strictly positive
            return 1e12

        # --- Sum of squared differences (the error function) ---
        sse = 0.0
        for t_i, y_i in zip(x, y):
            try:
                y_pred = _potential_parametric(t_i, mg, b, j, k, l, base)
                sse   += (y_pred - y_i) ** 2
            except (ValueError, ZeroDivisionError, OverflowError):
                return 1e12     # Catch any remaining numerical edge-cases

        return sse

    return objective


# ══════════════════════════════════════════════════════════════════════════════
# PUBLIC FITTER
# ══════════════════════════════════════════════════════════════════════════════

def fit_potential(
    x: np.ndarray,
    y: np.ndarray,
    initial_params: Optional[np.ndarray] = None,
    max_iter: int = 100_000,
    tol: float = 1e-9,
    verbose: bool = True,
) -> np.ndarray:
    """
    Fit the six parameters of potential(t) to observed (x, y) data by
    minimising the sum of squared differences between the model and the data.

    Parameters
    ----------
    x : array-like of float
        Time values.  Must be the same length as y.
    y : array-like of float
        Observed membrane potential values (mV).  Must be the same length as x.
    initial_params : array-like of float, optional
        Starting guess for [mg, b, j, k, l, base].
        Defaults to the values hardcoded in potential(t):
            [402.2442, 0.1662, 0.0261, 0.0771, 0.0570, -67.85]
        A good initial guess is important here — see IDENTIFIABILITY note
        in the module docstring.
    max_iter : int, optional
        Maximum Nelder-Mead iterations.  Default 100 000.
    tol : float, optional
        Absolute convergence tolerance on both parameter step (xatol) and
        objective step (fatol).  Default 1e-9.
    verbose : bool, optional
        If True, print a parameter table and fit quality summary.
        Default True.

    Returns
    -------
    params : np.ndarray of float, shape (6,)
        Optimised parameter array [mg, b, j, k, l, base].
        Order matches PARAM_NAMES and the order used in potential(t).

    Raises
    ------
    ValueError
        If x and y have different lengths, or if initial_params is the
        wrong length.
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    if x.shape != y.shape:
        raise ValueError(
            f"x and y must have equal length; got {x.shape} vs {y.shape}"
        )
    if len(x) < len(PARAM_NAMES):
        raise ValueError(
            f"Need at least {len(PARAM_NAMES)} data points to fit "
            f"{len(PARAM_NAMES)} parameters; got {len(x)}."
        )

    x0 = (
        np.asarray(initial_params, dtype=float)
        if initial_params is not None
        else INITIAL_PARAMS.copy()
    )
    if len(x0) != len(PARAM_NAMES):
        raise ValueError(
            f"initial_params must have length {len(PARAM_NAMES)}; got {len(x0)}."
        )

    objective = _make_objective(x, y)

    result: OptimizeResult = minimize(
        objective,
        x0      = x0,
        method  = "Nelder-Mead",
        options = {
            "maxiter":  max_iter,
            "xatol":    tol,      # Stop when parameter step falls below tol
            "fatol":    tol,      # Stop when objective step falls below tol
            "adaptive": True,     # Scales the simplex to each parameter's
                                  # magnitude — important here because mg (~400)
                                  # and j/k/l (~0.05) differ by four orders
            "disp":     False,
        },
    )

    fitted = result.x

    if verbose:
        _print_results(x0, fitted, result, len(x))

    return fitted


# ══════════════════════════════════════════════════════════════════════════════
# HELPER UTILITIES
# ══════════════════════════════════════════════════════════════════════════════

def _print_results(
    initial: np.ndarray,
    fitted:  np.ndarray,
    result:  OptimizeResult,
    n_points: int,
) -> None:
    """Print a formatted parameter table and fit quality summary."""
    col = 14
    sep = "─" * (8 + col * 3 + 4)
    print()
    print("  Fitted Parameters")
    print("  " + sep)
    print(f"  {'Param':<8} {'Initial':>{col}} {'Fitted':>{col}} {'Δ':>{col}}")
    print("  " + sep)
    for name, init, fit in zip(PARAM_NAMES, initial, fitted):
        print(f"  {name:<8} {init:{col}.6f} {fit:{col}.6f} {fit - init:+{col}.6f}")
    print("  " + sep)
    print(f"  Final SSE  : {result.fun:.6f}  (over {n_points} points)")
    print(f"  SSE/point  : {result.fun / n_points:.6f} mV²")
    print(f"  RMS error  : {m.sqrt(result.fun / n_points):.4f} mV")
    print(f"  Converged  : {result.success}")
    if not result.success:
        print(f"  [WARNING]  : {result.message}")
    print()


def evaluate(t_array: np.ndarray, params: np.ndarray) -> np.ndarray:
    """
    Evaluate the fitted model over an array of time values.

    Convenience wrapper — vectorises _potential_parametric across t_array
    using the parameter array returned by fit_potential().

    Parameters
    ----------
    t_array : array-like of float
        Time values at which to evaluate the model.
    params : array-like of float, shape (6,)
        [mg, b, j, k, l, base] as returned by fit_potential().

    Returns
    -------
    np.ndarray of float, same shape as t_array.
    """
    params  = np.asarray(params, dtype=float)
    t_array = np.asarray(t_array, dtype=float)
    mg, b, j, k, l, base = params
    return np.array([_potential_parametric(t, mg, b, j, k, l, base)
                     for t in t_array])


# ══════════════════════════════════════════════════════════════════════════════
# DEMO
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("Action Potential Curve Fitter — Demo")
    print("=" * 52)

    # Generate data from the original potential() function and add noise.
    # This is representative of fitting to a real AP trace that follows the
    # same ODE model.
    t_demo   = np.linspace(4.90, 25.0, 400)
    y_clean  = np.array([potential(t) for t in t_demo])

    rng      = np.random.default_rng(seed=7)
    sigma    = 0.3                                   # mV noise std dev
    y_noisy  = y_clean + rng.normal(0.0, sigma, size=len(t_demo))

    print(f"\n  Data    : {len(t_demo)} points, "
          f"t ∈ [{t_demo[0]:.2f}, {t_demo[-1]:.2f}] ms")
    print(f"  Noise σ : {sigma} mV")
    print(f"  Noise floor (n·σ²): {len(t_demo) * sigma**2:.2f}\n")

    # Fit — uses INITIAL_PARAMS as x0 (the hardcoded values from potential())
    fitted_params = fit_potential(t_demo, y_noisy)

    # Check how well the fitted model reproduces the noiseless ground truth
    y_fitted     = evaluate(t_demo, fitted_params)
    residuals    = np.abs(y_fitted - y_clean)
    print(f"  Fit quality vs noiseless ground truth:")
    print(f"    Max residual : {residuals.max():.4f} mV")
    print(f"    Mean residual: {residuals.mean():.4f} mV")
    print()
    print(f"  Fitted params array: {fitted_params}")